# 2-1. Python Basic
updated 0907  
numpy, 

In [1]:
# numpy asrray
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

# numpy attribute
print(a.shape)
print(a.ndim)    # 차원
print(a.dtype)
print(a.itemsize)     # 데이터 크기, 8바이트
print(a.size)     # 원소 몇개가 들어있는지, 차원 관계 없음
print(type(a))

# reshape
a.reshape(5,3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

arange 는 numpy가 제공하는 range 함수, 
keras 나 sklearn에서 대부분 numpy array로 줌

In [2]:
# ndarray 생성
a = np.array([[1,2,3],[4,5,6]])
b = np.zeros((3,4))
c = np.ones((2,3,4), dtype = np.int64)     # 3*4 를 2개 만듦
d = np.empty((2,3))
e = np.arange(10,100,10)     # 10부터 100까지 10단위로 끊어서

a,b,c,d,e

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 array([[-2.31584178e+077, -2.32036017e+077,  1.48219694e-323],
        [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [3]:
# ndarray arithmetic operations
# elementwise operations
A = np.array([20,30,40,50])
B = np.array(4)
C = A-B
D = B**2
print(A<35)
A,B,C,D

[ True  True False False]


(array([20, 30, 40, 50]), array(4), array([16, 26, 36, 46]), 16)

벡터화 연산 적용 가능, for loop 보다 빠른 실행 <- 병렬처리 가능  
최종에서는 array 형태로 넣어준다. 빨라서

In [4]:
# ndarray 벡터화 계산
# vectorized computation 효과
import time

# for
a = range(10000000)
b = range(10000000)
c = []

start = time.time()
for i in range(10000000):
    c.append(a[i]*b[i])
end = time.time()
print('elasped time = ', end-start)

# numpy 
a = np.arange(10000000)
b = np.arange(10000000)

start = time.time()
c = a*b
end = time.time()

print('elasped time = ', end-start)

elasped time =  3.0413289070129395
elasped time =  0.16149592399597168


In [5]:
# ndarray matrix-wise operaions
A = np.array([[1,1],
            [0,1]])
B = np.array([[2,0],
            [3,4]])

C = A*B     # elementwise product
D = A@B     # matrix product

X = [1,2,3,4]
Y = [1,0,1,0]
F = np.inner(X,Y)      # inner product, 내적

A,B,C,D,X,Y,F

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]),
 array([[2, 0],
        [0, 4]]),
 array([[5, 4],
        [3, 4]]),
 [1, 2, 3, 4],
 [1, 0, 1, 0],
 4)

### Pandas & DataFrame
- pandas : python data analysis library  
- dataframe : pandas 가 제공하는 테이블 형태의 데이터 분석을 위한 자료구조  
- nparray, dict, list 등과 데이터 호환 및 변환 가능  
- excel file 로 된 데이터 파일을 쉽게 import 할 수 있다는 장점

In [ ]:
# excel 파일 읽어들이기
# pandas 로 엑셀 불러들이기는 자습

### SQL with python

In [1]:
import pymysql

In [2]:
conn = pymysql.connect(host='localhost', user = 'root', password='1234')
curs = conn.cursor(pymysql.cursors.DictCursor)

sql = 'select * from university.student'
curs.execute(sql)

row = curs.fetchone()
while row:
    print(row)
    row = curs.fetchone()
curs.close()

{'sno': 100, 'sname': 'Kim', 'dept': 'CE', 'enter_year': 2015, 'enter_date': datetime.datetime(2020, 9, 9, 1, 10, 6)}
{'sno': 200, 'sname': 'Lee', 'dept': 'CE', 'enter_year': 2016, 'enter_date': datetime.datetime(2020, 9, 9, 1, 10, 6)}
{'sno': 300, 'sname': 'Jang', 'dept': 'MA', 'enter_year': 2017, 'enter_date': datetime.datetime(2020, 9, 9, 1, 10, 6)}
{'sno': 400, 'sname': 'Park', 'dept': 'IE', 'enter_year': 2018, 'enter_date': datetime.datetime(2020, 9, 9, 1, 10, 6)}


튜플 하나가 딕셔너리로 들어가있음.  
key가 column, values 가 실제 값, 실제 만들어진 시간 들어가 있음.

## Python 과제
1. 엑셀 파일 db_score.xlsx 를 입력파일로 받아서 dataframe으로 읽어 들이고,   
이 데이터들을 mysql db_score 테이블을 생성하고 모두 튜플로 추가하는 python 프로그램을 작성할 것.  
2. db_score 테이블로 부터 midterm(중간고사) 와 final(기말고사) 가 모두 20점 이상인 학생의  
학번, 중간고사, 기말고사를 학번 순으로 출력하는 python 프로그램을 작성할 것

> - 1,2는 각각 python 프로그램으로 작성할 것  
> - 제출재용 : 개발설명, 소스코드, 실행 결과 캡쳐  
> -  제출마감 : 9월 14일(월) 자정